import test from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
const { ConsensusService }=require('../dist/consensus.service.js');
const { StatisticsService }=require('../dist/statistics.service.js');
const { IdentityService }=require('../dist/identity.service.js');
const { EventValidationService }=require('../dist/event-validation.service.js');
const base={matchId:'m1',eventType:'GOAL',matchSecond:120,subjectId:'p1',payload:{team:'home',score:1},contributorId:'c1',clientEventId:'e1'};
test('one observation stays pending',()=>{const result=new ConsensusService().score(base,[]);assert.equal(result.publishable,false);assert.equal(result.agreeingSources,1)});
test('independent matching source establishes consensus',()=>{const peer={...base,contributorId:'c2',clientEventId:'e2',payload:{score:1,team:'home'}};assert.equal(new ConsensusService().score(base,[peer]).publishable,true)});
test('same contributor cannot establish consensus',()=>{assert.equal(new ConsensusService().score(base,[{...base,clientEventId:'e2'}]).publishable,false)});
test('conflicting independent observation requires review',()=>{const result=new ConsensusService().score(base,[{...base,contributorId:'c2',payload:{score:2,team:'home'}}]);assert.equal(result.conflictingSources,1)});
test('club records respect filters',()=>{const facts=[{type:'MATCH_RESULT',teamId:'t1',seasonId:'2026',venueId:'v1',location:'HOME',outcome:'WIN'},{type:'GOAL',teamId:'t1',seasonId:'2026',venueId:'v1',location:'HOME'}];const result=new StatisticsService().clubRecords('t1',facts,{seasonId:'2026',location:'HOME'});assert.deepEqual({matches:result.matches,wins:result.wins,goals:result.goals,points:result.points},{matches:1,wins:1,goals:1,points:3})});
test('canonical participant resolves through database',async()=>{const db={match:{findUnique:async()=>({id:'m1'})},player:{findUnique:async({where})=>where.id==='p1'?{id:'p1'}:null}};const identity=await new IdentityService(db).resolve({matchId:'m1',playerId:'p1'});assert.equal(identity.playerId,'p1')});
test('name normalization is stable',()=>{const service=new IdentityService({});assert.equal(service.normalizeName('Tendai Mùsóna'),service.normalizeName('tendai-musona'))});
test('unknown player IDs are rejected',async()=>{const db={match:{findUnique:async()=>({id:'m1'})},player:{findUnique:async()=>null}};await assert.rejects(()=>new IdentityService(db).resolve({matchId:'m1',playerId:'missing'}),/Unknown canonical playerId/)});
test('possession duration sums to 100 percent',()=>{const result=new StatisticsService().aggregateMatch([{type:'POSSESSION_INTERVAL',teamId:'home',payload:{durationSeconds:60}},{type:'POSSESSION_INTERVAL',teamId:'away',payload:{durationSeconds:40}}]);assert.equal(result.teams.home.possessionPercentage,60);assert.equal(result.teams.away.possessionPercentage,40)});
test('advanced events aggregate correctly',()=>{const result=new StatisticsService().aggregateMatch([{type:'GOAL',teamId:'home',payload:{scoringMethod:'LEFT_FOOT'}},{type:'CORNER',teamId:'home',payload:{}},{type:'PENALTY',teamId:'home',payload:{outcome:'SCORED'}}]);assert.equal(result.teams.home.goals,1);assert.equal(result.teams.home.corners,1);assert.equal(result.teams.home.penalties.scored,1)});
test('event validation rejects impossible distances',()=>{const events=new EventValidationService();assert.throws(()=>events.validate('FREE_KICK',{team:'home',distanceMeters:150,outcome:'TAKEN'}),/distanceMeters/)});
