'use client';
import Link from 'next/link';
import { Activity, ArrowRight, BarChart3, CalendarDays, CheckCircle2, Clock3, Database, MapPin, ShieldCheck, Trophy, Users } from 'lucide-react';
import { Card, SectionHead, TeamBadge } from '@/components/ui';
import { formatDate, initials, useApi } from '@/lib/api';
type Overview={season:any;matches:any[];standings:any[];players:any[];transfers:any[];articles:any[];metrics:{matches:number;events:number;contributors:number}};
export default function Home(){const {data,error,loading}=useApi<Overview>('/public/overview');if(loading)return <main className="page-shell"><p>Loading verified football data…</p></main>;if(error||!data)return <main className="page-shell"><div className="empty-state"><Database/><b>Football database unavailable</b><span>{error||'Add a competition and season to begin.'}</span></div></main>;const live=data.matches.find(match=>match.status==='LIVE')??data.matches[0];return <main>
  <section className="hero"><div className="hero-grid"><div><span className="kicker"><span/> {data.season?.competition?.name??'ZIMBABWE FOOTBALL'} · {data.season?.label??'CURRENT SEASON'}</span><h1>Football data<br/><em>in context.</em></h1><p>Live scores, fixtures, standings and verified match events rendered directly from the TechnSports database.</p><div className="hero-actions"><Link href="/scores" className="primary"><Activity/> Live scores</Link><Link href="/fixtures" className="secondary">View fixtures <ArrowRight/></Link></div></div>{live?<div className="pulse-card"><div className="pulse-top"><div><span className="live-dot"/> {live.status}</div><span>{live.season.competition.name}</span></div><div className="score-stage"><div><TeamBadge short={live.homeTeam.shortName} color={live.homeTeam.primaryColor}/><strong>{live.homeTeam.name}</strong></div><div className="hero-score"><b>{live.homeScore}</b><span>—</span><b>{live.awayScore}</b><small>{live.round??live.status}</small></div><div><TeamBadge short={live.awayTeam.shortName} color={live.awayTeam.primaryColor}/><strong>{live.awayTeam.name}</strong></div></div><Link href={`/matches/${live.id}`}>Open match centre <ArrowRight/></Link></div>:<Card className="pulse-card"><div className="empty-state"><CalendarDays/><b>No fixtures yet</b><span>Add the first fixture in administration.</span></div></Card>}</div></section>
  <div className="trust-strip"><span><Database/> {data.metrics.events} verified events</span><span><Users/> {data.metrics.contributors} verified contributors</span><span><ShieldCheck/> Multi-source verification</span><span><BarChart3/> {data.metrics.matches} season matches</span></div>
  <section className="content"><div className="toolbar"><div className="competition"><Trophy/><div><small>COMPETITION</small><b>{data.season?.competition?.name}</b></div></div><b>{data.season?.label}</b></div>
  <SectionHead eyebrow="MATCH CENTRE" title="Recent & upcoming" action="All fixtures" href="/fixtures"/><div className="fixture-grid">{data.matches.slice(0,6).map(match=><Link key={match.id} href={`/matches/${match.id}`} className={`fixture-card ${match.status==='LIVE'?'is-live':''}`}><div className="fixture-meta"><span className={match.status==='LIVE'?'status-live':''}>{match.status}</span><span><MapPin/>{match.venue?.name??match.venueName??'Venue TBC'}</span></div><div className="fixture-team"><span><TeamBadge small short={match.homeTeam.shortName} color={match.homeTeam.primaryColor}/>{match.homeTeam.name}</span><b>{match.status==='SCHEDULED'?'–':match.homeScore}</b></div><div className="fixture-team"><span><TeamBadge small short={match.awayTeam.shortName} color={match.awayTeam.primaryColor}/>{match.awayTeam.name}</span><b>{match.status==='SCHEDULED'?'–':match.awayScore}</b></div><div className="fixture-foot"><span><Clock3/>{formatDate(match.kickoffAt)}</span><span>Match centre</span></div></Link>)}</div>
  <div className="dashboard-grid"><div><SectionHead eyebrow={data.season?.label??'SEASON'} title="League table" action="Full table"/><Card className="table-card"><div className="table-row table-head"><span>#</span><span>CLUB</span><span>P</span><span>GD</span><span>PTS</span><span>FORM</span></div>{data.standings.slice(0,8).map(row=><div className="table-row" key={row.team.id}><span className={row.position<=3?'qualify':''}>{row.position}</span><span><TeamBadge small short={row.team.shortName} color={row.team.primaryColor}/><Link href={`/clubs/${row.team.slug}`}><b>{row.team.name}</b></Link></span><span>{row.played}</span><span>{row.goalDifference>0?`+${row.goalDifference}`:row.goalDifference}</span><strong>{row.points}</strong><span className="form">{row.form.map((value:string,index:number)=><i className={value.toLowerCase()} key={index}>{value}</i>)}</span></div>)}</Card></div><aside><SectionHead eyebrow="DATABASE" title="Coverage"/><div className="metric-grid"><Card><Database/><strong>{data.metrics.events}</strong><span>VERIFIED EVENTS</span></Card><Card><CalendarDays/><strong>{data.metrics.matches}</strong><span>MATCHES</span></Card><Card><Users/><strong>{data.metrics.contributors}</strong><span>CONTRIBUTORS</span></Card><Card><CheckCircle2/><strong>{data.standings.length}</strong><span>REGISTERED CLUBS</span></Card></div></aside></div>
  <section id="players"><SectionHead eyebrow="PLAYER INDEX" title="Top scorers" action="Explore all players"/><Card className="players-table"><div className="player-row player-head"><span>RANK</span><span>PLAYER</span><span>APPS</span><span>GOALS</span><span>ASSISTS</span><span>CLUB</span></div>{data.players.map((player,index)=><Link href={`/players/${player.slug}`} className="player-row" key={player.id}><span>{index+1}</span><span><i>{initials(player.name)}</i><span><b>{player.name}</b><small>{player.position} · {player.team?.name??'Unregistered'}</small></span></span><span>{player.appearances}</span><strong>{player.goals}</strong><span>{player.assists}</span><em>{player.team?.shortName??'—'}</em></Link>)}</Card></section>
  <section id="news"><SectionHead eyebrow="EDITORIAL" title="Latest stories" action="All stories"/><div className="story-grid">{data.articles.slice(0,3).map(article=><Link className="story" href={`/news/${article.slug}`} key={article.slug}><div className="story-art" style={article.coverImageUrl?{backgroundImage:`url(${article.coverImageUrl})`}:undefined}/><div><span className="story-tag">{article.category}</span><h3>{article.title}</h3><p>{article.excerpt}</p><small>{article.publishedAt?formatDate(article.publishedAt):''}</small></div></Link>)}</div></section>
  </section>
  <section className="join"><div><span className="kicker"><span/> MATCH DATA NETWORK</span><h2>Collect verified match data.</h2><p>Assigned contributors record lineups, events and team statistics. Independent reports are compared before publication.</p><Link href="/contribute" className="primary">View assignments <ArrowRight/></Link></div></section>
  </main>}
