'use client';
type QueuedRequest={id:string;url:string;payload:unknown;headers:Record<string,string>;createdAt:string;attempts:number};
const DB='technsports-offline';const STORE='requests';
function database(){return new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open(DB,1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains(STORE))request.result.createObjectStore(STORE,{keyPath:'id'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function save(item:QueuedRequest){const db=await database();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(item);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close();window.dispatchEvent(new Event('technsports-queue-change'))}
async function remove(id:string){const db=await database();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close()}
export async function queuedRequests(){const db=await database();const items=await new Promise<QueuedRequest[]>((resolve,reject)=>{const request=db.transaction(STORE).objectStore(STORE).getAll();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});db.close();return items.sort((a,b)=>a.createdAt.localeCompare(b.createdAt))}
export async function queueCount(){return (await queuedRequests()).length}
export async function submitOrQueue(url:string,payload:unknown,headers:Record<string,string>={'Content-Type':'application/json'}){const item:QueuedRequest={id:crypto.randomUUID(),url,payload,headers,createdAt:new Date().toISOString(),attempts:0};if(!navigator.onLine){await save(item);return {queued:true,status:'QUEUED',queueId:item.id}}try{const response=await fetch(url,{method:'POST',headers,credentials:'include',body:JSON.stringify(payload)});const body=await response.json().catch(()=>({}));if(response.ok)return {...body,queued:false};if(response.status>=500){await save(item);return {queued:true,status:'QUEUED',queueId:item.id}}throw new Error(Array.isArray(body.message)?body.message.join(', '):body.message||`Request failed: ${response.status}`)}catch(error){if(error instanceof TypeError){await save(item);return {queued:true,status:'QUEUED',queueId:item.id}}throw error}}
export async function flushQueue(){if(!navigator.onLine)return {sent:0,remaining:await queueCount()};let sent=0;for(const item of await queuedRequests()){try{const response=await fetch(item.url,{method:'POST',headers:item.headers,credentials:'include',body:JSON.stringify(item.payload)});if(response.ok||response.status===409){await remove(item.id);sent++}}catch{break}}window.dispatchEvent(new Event('technsports-queue-change'));return {sent,remaining:await queueCount()}}
