import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { AssignmentScope, IdentityClaimStatus, MatchStatus, ParticipantSource, Prisma, SubmissionStatus, TransferType, UserRole } from '@prisma/client';
import { PrismaService } from './prisma.service';
export type CreateCompetitionInput={name:string;countryCode:string};
export type CreateSeasonInput={label:string;startsAt:string;endsAt:string};
export type CreateTeamInput={name:string;shortName:string;crestUrl?:string;city?:string;foundedYear?:number;websiteUrl?:string;primaryColor?:string;secondaryColor?:string};
export type CreateFixtureInput={seasonId:string;homeTeamId:string;awayTeamId:string;kickoffAt:string;round?:string;venueName?:string;venueId?:string};
export type CreateArticleInput={title:string;excerpt:string;body:string;category:string;status:'DRAFT'|'PUBLISHED';authorName?:string;coverImageUrl?:string;relatedPlayerIds?:string[]};
export type CreateVenueInput={name:string;city:string;countryCode?:string;latitude?:number;longitude?:number};
export type CreatePlayerInput={legalName:string;knownAs?:string;dateOfBirth?:string;nationalityCode?:string;preferredFoot?:string;photoUrl?:string;position:string};
export type PlayerRegistrationInput={playerId:string;teamId:string;seasonId:string;shirtNumber?:number;startsAt:string;endsAt?:string};
export type UpdateFixtureInput={kickoffAt?:string;round?:string;venueName?:string;venueId?:string;status?:'SCHEDULED'|'LIVE'|'SUSPENDED'|'POSTPONED'|'ABANDONED'|'FINISHED';homeScore?:number;awayScore?:number};
export type LineupInput={teamId:string;playerIds:string[]};
export type AssignmentInput={matchId:string;userId:string;scope:'LINEUPS'|'TIMELINE'|'PLAYER_ACTIONS'|'TEAM_STATS'|'MEDIA'};
@Injectable()
export class AdministrationService {
  constructor(private readonly db:PrismaService){}
  private slug(value:string){return value.toLowerCase().trim().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
  private databaseError(error:unknown):never{if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002')throw new ConflictException('A record with these identifying fields already exists');throw error}
  async createCompetition(input:CreateCompetitionInput){const name=input.name.trim(),countryCode=input.countryCode.trim().toUpperCase();const existing=await this.db.competition.findFirst({where:{name:{equals:name,mode:'insensitive'},countryCode}});if(existing)throw new ConflictException('Competition already exists in this country');return this.db.competition.create({data:{name,countryCode}}).catch(error=>this.databaseError(error))}
  listCompetitions(){return this.db.competition.findMany({include:{seasons:{orderBy:{startsAt:'desc'}}},orderBy:{name:'asc'}})}
  async createSeason(competitionId:string,input:CreateSeasonInput){const startsAt=new Date(input.startsAt),endsAt=new Date(input.endsAt);if(startsAt>=endsAt)throw new BadRequestException('Season end date must be after its start date');if(!await this.db.competition.findUnique({where:{id:competitionId}}))throw new NotFoundException('Competition not found');return this.db.season.create({data:{competitionId,label:input.label.trim(),startsAt,endsAt}}).catch(error=>this.databaseError(error))}
  async createVenue(input:CreateVenueInput){const name=input.name.trim(),city=input.city.trim(),slug=this.slug(`${name}-${city}`);if(!slug)throw new BadRequestException('Venue name is invalid');return this.db.venue.create({data:{name,slug,city,countryCode:(input.countryCode??'ZW').trim().toUpperCase(),latitude:input.latitude,longitude:input.longitude}}).catch(error=>this.databaseError(error))}
  listVenues(){return this.db.venue.findMany({orderBy:[{city:'asc'},{name:'asc'}]})}
  async createTeam(input:CreateTeamInput){const name=input.name.trim(),slug=this.slug(name);if(!slug)throw new BadRequestException('Team name is invalid');return this.db.team.create({data:{name,slug,shortName:input.shortName.trim().toUpperCase(),crestUrl:input.crestUrl?.trim(),city:input.city?.trim(),foundedYear:input.foundedYear,websiteUrl:input.websiteUrl?.trim(),primaryColor:input.primaryColor,secondaryColor:input.secondaryColor}}).catch(error=>this.databaseError(error))}
  listTeams(){return this.db.team.findMany({orderBy:{name:'asc'}})}
  async createPlayer(input:CreatePlayerInput){const legalName=input.legalName.trim(),knownAs=input.knownAs?.trim();const slug=this.slug(knownAs||legalName);if(!slug)throw new BadRequestException('Player name is invalid');return this.db.player.create({data:{legalName,knownAs:knownAs||undefined,slug,dateOfBirth:input.dateOfBirth?new Date(input.dateOfBirth):undefined,nationalityCode:(input.nationalityCode??'ZW').trim().toUpperCase(),preferredFoot:input.preferredFoot?.trim(),photoUrl:input.photoUrl?.trim(),position:input.position.trim().toUpperCase()}}).catch(error=>this.databaseError(error))}
  listPlayers(q?:string){const query=q?.trim();return this.db.player.findMany({where:query?{OR:[{legalName:{contains:query,mode:'insensitive'}},{knownAs:{contains:query,mode:'insensitive'}}]}:undefined,include:{registrations:{include:{team:true},orderBy:{startsAt:'desc'},take:3}},orderBy:{legalName:'asc'},take:query?50:300})}
  async registerPlayer(input:PlayerRegistrationInput){const startsAt=new Date(input.startsAt),endsAt=input.endsAt?new Date(input.endsAt):undefined;if(endsAt&&startsAt>=endsAt)throw new BadRequestException('Registration end date must be after start date');const [player,team,season,seasonTeam]=await Promise.all([this.db.player.findUnique({where:{id:input.playerId}}),this.db.team.findUnique({where:{id:input.teamId}}),this.db.season.findUnique({where:{id:input.seasonId}}),this.db.seasonTeam.findUnique({where:{seasonId_teamId:{seasonId:input.seasonId,teamId:input.teamId}}})]);if(!player)throw new NotFoundException('Player not found');if(!team)throw new NotFoundException('Team not found');if(!season)throw new NotFoundException('Season not found');if(!seasonTeam)throw new BadRequestException('Club must be registered in the selected season first');if(startsAt<season.startsAt||startsAt>season.endsAt)throw new BadRequestException('Registration start date must fall inside the season');const overlap=await this.db.playerRegistration.findFirst({where:{playerId:input.playerId,seasonId:input.seasonId,OR:[{endsAt:null},{endsAt:{gte:startsAt}}]}});if(overlap)throw new ConflictException('Player already has an overlapping registration in this season');return this.db.playerRegistration.create({data:{playerId:input.playerId,teamId:input.teamId,seasonId:input.seasonId,shirtNumber:input.shirtNumber,startsAt,endsAt},include:{player:true,team:true}})}
  async registerTeam(seasonId:string,teamId:string){const [season,team]=await Promise.all([this.db.season.findUnique({where:{id:seasonId}}),this.db.team.findUnique({where:{id:teamId}})]);if(!season)throw new NotFoundException('Season not found');if(!team)throw new NotFoundException('Team not found');return this.db.seasonTeam.create({data:{seasonId,teamId},include:{team:true}}).catch(error=>this.databaseError(error))}
  seasonTeams(seasonId:string){return this.db.seasonTeam.findMany({where:{seasonId},include:{team:true},orderBy:{team:{name:'asc'}}})}
  async createFixture(input:CreateFixtureInput){if(input.homeTeamId===input.awayTeamId)throw new BadRequestException('Home and away teams must be different');const kickoffAt=new Date(input.kickoffAt);const season=await this.db.season.findUnique({where:{id:input.seasonId}});if(!season)throw new NotFoundException('Season not found');if(kickoffAt<season.startsAt||kickoffAt>season.endsAt)throw new BadRequestException('Kickoff must fall within the selected season dates');if(input.venueId&&!await this.db.venue.findUnique({where:{id:input.venueId}}))throw new NotFoundException('Venue not found');const registered=await this.db.seasonTeam.count({where:{seasonId:input.seasonId,teamId:{in:[input.homeTeamId,input.awayTeamId]}}});if(registered!==2)throw new BadRequestException('Both clubs must be registered in the selected season');return this.db.match.create({data:{seasonId:input.seasonId,homeTeamId:input.homeTeamId,awayTeamId:input.awayTeamId,kickoffAt,round:input.round?.trim(),venueName:input.venueName?.trim(),venueId:input.venueId||undefined,status:MatchStatus.SCHEDULED},include:{homeTeam:true,awayTeam:true,season:{include:{competition:true}},venue:true}}).catch(error=>this.databaseError(error))}
  async updateFixture(id:string,input:UpdateFixtureInput){const match=await this.db.match.findUnique({where:{id},include:{season:true}});if(!match)throw new NotFoundException('Fixture not found');if(input.venueId&&!await this.db.venue.findUnique({where:{id:input.venueId}}))throw new NotFoundException('Venue not found');const kickoffAt=input.kickoffAt?new Date(input.kickoffAt):undefined;if(kickoffAt&&(kickoffAt<match.season.startsAt||kickoffAt>match.season.endsAt))throw new BadRequestException('Kickoff must fall within the selected season dates');return this.db.match.update({where:{id},data:{kickoffAt,round:input.round?.trim(),venueName:input.venueName?.trim(),venueId:input.venueId||undefined,status:input.status as MatchStatus|undefined,homeScore:input.homeScore,awayScore:input.awayScore},include:{homeTeam:true,awayTeam:true,venue:true,season:{include:{competition:true}}}})}
  fixtures(seasonId?:string){return this.db.match.findMany({where:{seasonId:seasonId||undefined},include:{homeTeam:true,awayTeam:true,venue:true,season:{include:{competition:true}},participants:{include:{player:true,team:true}}},orderBy:{kickoffAt:'asc'},take:300})}
  async setLineup(matchId:string,input:LineupInput){const playerIds=[...new Set(input.playerIds.filter(Boolean))];if(!playerIds.length)throw new BadRequestException('At least one player is required');if(playerIds.length>23)throw new BadRequestException('A match squad cannot exceed 23 players for one team');const match=await this.db.match.findUnique({where:{id:matchId}});if(!match)throw new NotFoundException('Fixture not found');if(input.teamId!==match.homeTeamId&&input.teamId!==match.awayTeamId)throw new BadRequestException('Lineup team must be one of the match clubs');const registered=await this.db.playerRegistration.findMany({where:{seasonId:match.seasonId,teamId:input.teamId,playerId:{in:playerIds}},select:{playerId:true,shirtNumber:true}});if(registered.length!==playerIds.length)throw new BadRequestException('Every lineup player must be registered to this club in this season');const shirtNumbers=new Map(registered.map(item=>[item.playerId,item.shirtNumber]));return this.db.$transaction(async tx=>{await tx.matchParticipant.deleteMany({where:{matchId,teamId:input.teamId,source:ParticipantSource.CONFIRMED_LINEUP,playerId:{notIn:playerIds}}});for(const playerId of playerIds){await tx.matchParticipant.upsert({where:{matchId_playerId:{matchId,playerId}},update:{teamId:input.teamId,source:ParticipantSource.CONFIRMED_LINEUP,confirmed:true,shirtNumber:shirtNumbers.get(playerId)},create:{matchId,playerId,teamId:input.teamId,source:ParticipantSource.CONFIRMED_LINEUP,confirmed:true,shirtNumber:shirtNumbers.get(playerId)}})}return tx.matchParticipant.findMany({where:{matchId,teamId:input.teamId},include:{player:true,team:true},orderBy:{shirtNumber:'asc'}})})}
  async assignCollector(input:AssignmentInput){const [match,user]=await Promise.all([this.db.match.findUnique({where:{id:input.matchId},include:{homeTeam:true,awayTeam:true}}),this.db.user.findUnique({where:{id:input.userId}})]);if(!match)throw new NotFoundException('Fixture not found');if(!user)throw new NotFoundException('User not found');if(user.role===UserRole.SUPPORTER)throw new BadRequestException('Only collector, reviewer, editor or admin users can receive match assignments');return this.db.assignment.upsert({where:{matchId_userId_scope:{matchId:input.matchId,userId:input.userId,scope:input.scope as AssignmentScope}},update:{acceptedAt:new Date(),completedAt:null},create:{matchId:input.matchId,userId:input.userId,scope:input.scope as AssignmentScope,acceptedAt:new Date()},include:{user:{select:{id:true,username:true,displayName:true,role:true}},match:{include:{homeTeam:true,awayTeam:true,venue:true,season:{include:{competition:true}}}}}})}
  async createArticle(input:CreateArticleInput){const title=input.title.trim(),slug=this.slug(title);if(!slug)throw new BadRequestException('Article title cannot produce a valid slug');const playerIds=[...new Set(input.relatedPlayerIds??[])];if(playerIds.length&&await this.db.player.count({where:{id:{in:playerIds}}})!==playerIds.length)throw new BadRequestException('One or more related player IDs do not exist');return this.db.article.create({data:{slug,title,excerpt:input.excerpt.trim(),body:{format:'plain_text',text:input.body.trim()},category:input.category.trim().toUpperCase(),status:input.status,authorName:input.authorName?.trim()||'TechnSports Data Desk',coverImageUrl:input.coverImageUrl?.trim()||undefined,publishedAt:input.status==='PUBLISHED'?new Date():null,players:{create:playerIds.map(playerId=>({playerId}))}},include:{players:{include:{player:true}}}}).catch(error=>this.databaseError(error))}
  articles(){return this.db.article.findMany({where:{status:'PUBLISHED',deletedAt:null},select:{slug:true,title:true,excerpt:true,category:true,authorName:true,coverImageUrl:true,publishedAt:true},orderBy:{publishedAt:'desc'}})}
  async article(slug:string){const article=await this.db.article.findFirst({where:{slug,status:'PUBLISHED',deletedAt:null},include:{players:{include:{player:true}}}});if(!article)throw new NotFoundException('Published article not found');return article}
  async reviewQueue(){const [observations,transfers,identityClaims,articles,setting]=await Promise.all([this.db.observation.findMany({where:{status:{in:[SubmissionStatus.PENDING,SubmissionStatus.CONFLICT]}},include:{match:{include:{homeTeam:true,awayTeam:true}},contributor:{select:{id:true,username:true,displayName:true}},player:true,identityClaim:true},orderBy:{receivedAt:'desc'},take:100}),this.db.transferContribution.findMany({where:{status:{in:[SubmissionStatus.PENDING,SubmissionStatus.CONSENSUS]}},orderBy:{receivedAt:'desc'},take:100}),this.db.playerIdentityClaim.findMany({where:{status:IdentityClaimStatus.PENDING},include:{team:true,season:true,observations:{take:5,include:{match:{include:{homeTeam:true,awayTeam:true}},contributor:{select:{username:true,displayName:true}}}}},orderBy:{createdAt:'desc'},take:100}),this.db.article.findMany({where:{source:'CONTRIBUTOR',status:{in:['PENDING','REJECTED']},deletedAt:null},include:{match:{include:{homeTeam:true,awayTeam:true}},authorUser:{select:{id:true,username:true,displayName:true,role:true}},_count:{select:{comments:true,reactions:true}}},orderBy:{createdAt:'desc'},take:100}),this.db.siteSetting.findUnique({where:{key:'contributorArticleAutoApprove'}})]);return{observations:observations.map(item=>({...item,payload:item.payload,contributor:item.contributor})),transfers:transfers.map(item=>this.serializeTransferContribution(item)),identityClaims,articles,settings:{contributorArticleAutoApprove:Boolean((setting?.value as any)?.enabled)}}}
  async setContributorArticleAutoApprove(enabled:boolean){return this.db.siteSetting.upsert({where:{key:'contributorArticleAutoApprove'},update:{value:{enabled}},create:{key:'contributorArticleAutoApprove',value:{enabled}}})}
  async approveArticle(id:string,approvedById?:string){const article=await this.db.article.findUnique({where:{id}});if(!article)throw new NotFoundException('Article not found');return this.db.article.update({where:{id},data:{status:'PUBLISHED',publishedAt:article.publishedAt??new Date(),approvedAt:new Date(),approvedById,moderationNote:null}})}
  async rejectArticle(id:string,reason?:string){return this.db.article.update({where:{id},data:{status:'REJECTED',moderationNote:reason?.trim()||'Rejected by reviewer'}})}
  async deleteArticle(id:string,reason?:string){return this.db.article.update({where:{id},data:{status:'DELETED',deletedAt:new Date(),moderationNote:reason?.trim()||'Deleted by reviewer'}})}
  async approveObservation(id:string){const observation=await this.db.observation.findUnique({where:{id}});if(!observation)throw new NotFoundException('Observation not found');return this.db.$transaction(async tx=>{const updated=await tx.observation.update({where:{id},data:{status:SubmissionStatus.APPROVED}});const existing=await tx.matchFact.findFirst({where:{matchId:observation.matchId,factType:observation.eventType,subjectId:observation.subjectId,matchSecond:observation.matchSecond}});const fact=existing??await tx.matchFact.create({data:{matchId:observation.matchId,factType:observation.eventType,subjectId:observation.subjectId,matchSecond:observation.matchSecond,value:observation.payload as Prisma.InputJsonValue,confidence:0.7,sourceCount:1,publishedAt:new Date()}});return{observation:updated,fact}})}
  async rejectObservation(id:string,_reason?:string){return this.db.observation.update({where:{id},data:{status:SubmissionStatus.REJECTED}})}
  async approveTransfer(id:string){const contribution=await this.db.transferContribution.findUnique({where:{id}});if(!contribution)throw new NotFoundException('Transfer contribution not found');return this.db.$transaction(async tx=>{const existing=await tx.transfer.findFirst({where:{playerId:contribution.playerId,fromTeamId:contribution.fromTeamId,toTeamId:contribution.toTeamId,type:contribution.type,effectiveAt:contribution.effectiveAt,feeMinor:contribution.feeMinor,feeCurrency:contribution.feeCurrency,verified:true}});const transfer=existing??await tx.transfer.create({data:{playerId:contribution.playerId,fromTeamId:contribution.fromTeamId,toTeamId:contribution.toTeamId,type:contribution.type as TransferType,announcedAt:contribution.receivedAt,effectiveAt:contribution.effectiveAt,verified:true,feeMinor:contribution.feeMinor,feeCurrency:contribution.feeCurrency,feeDisclosed:contribution.feeMinor!==null,sourceUrl:contribution.sourceUrl}});await tx.transferContribution.updateMany({where:{playerId:contribution.playerId,fromTeamId:contribution.fromTeamId,toTeamId:contribution.toTeamId,type:contribution.type,effectiveAt:contribution.effectiveAt},data:{status:SubmissionStatus.APPROVED}});return{transfer:{...transfer,feeMinor:transfer.feeMinor?.toString()}}})}
  async rejectTransfer(id:string,_reason?:string){const item=await this.db.transferContribution.update({where:{id},data:{status:SubmissionStatus.REJECTED}});return this.serializeTransferContribution(item)}
  async resolveIdentityClaim(id:string,playerId:string){const [claim,player]=await Promise.all([this.db.playerIdentityClaim.findUnique({where:{id}}),this.db.player.findUnique({where:{id:playerId}})]);if(!claim)throw new NotFoundException('Identity claim not found');if(!player)throw new NotFoundException('Player not found');return this.db.$transaction(async tx=>{const updated=await tx.playerIdentityClaim.update({where:{id},data:{status:IdentityClaimStatus.RESOLVED,resolvedPlayerId:playerId,resolvedAt:new Date()}});await tx.observation.updateMany({where:{identityClaimId:id},data:{playerId,subjectId:playerId}});return updated})}
  async rejectIdentityClaim(id:string,_reason?:string){return this.db.playerIdentityClaim.update({where:{id},data:{status:IdentityClaimStatus.REJECTED,resolvedAt:new Date()}})}
  private serializeTransferContribution(item:any){return{...item,feeMinor:item.feeMinor?.toString()}}
}
