import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { ParticipantSource } from '@prisma/client';
import { PrismaService } from './prisma.service';
@Injectable()
export class IdentityService {
  constructor(private readonly db:PrismaService){}
  async participants(matchId:string,side?:string){const match=await this.db.match.findUnique({where:{id:matchId},include:{participants:{include:{player:true}},homeTeam:true,awayTeam:true}});if(!match)throw new NotFoundException('Match not found');const teamId=side==='home'?match.homeTeamId:side==='away'?match.awayTeamId:undefined;if(match.participants.length)return match.participants.filter(item=>!teamId||item.teamId===teamId).map(item=>({id:item.playerId,name:item.player.knownAs??item.player.legalName,teamId:item.teamId===match.homeTeamId?'home':'away',shirtNumber:item.shirtNumber,position:item.player.position,source:item.source}));const registrations=await this.db.playerRegistration.findMany({where:{seasonId:match.seasonId,teamId:teamId??{in:[match.homeTeamId,match.awayTeamId]},startsAt:{lte:match.kickoffAt},OR:[{endsAt:null},{endsAt:{gte:match.kickoffAt}}]},include:{player:true}});return registrations.map(item=>({id:item.playerId,name:item.player.knownAs??item.player.legalName,teamId:item.teamId===match.homeTeamId?'home':'away',shirtNumber:item.shirtNumber,position:item.player.position,source:ParticipantSource.SEASON_REGISTRATION}))}
  normalizeName(name:string){return name.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
  async resolve(input:{matchId:string;playerId?:string;unlistedPlayerName?:string;teamId?:string}){const match=await this.db.match.findUnique({where:{id:input.matchId}});if(!match)throw new NotFoundException('Match not found');if(input.playerId){const player=await this.db.player.findUnique({where:{id:input.playerId}});if(!player)throw new BadRequestException('Unknown canonical playerId');return{subjectId:player.id,playerId:player.id,identityStatus:'CANONICAL' as const}}if(input.unlistedPlayerName&&input.teamId){const normalized=this.normalizeName(input.unlistedPlayerName);if(normalized.length<3)throw new BadRequestException('Unlisted player name is too short');const canonicalTeamId=input.teamId==='home'?match.homeTeamId:input.teamId==='away'?match.awayTeamId:input.teamId;const claim=await this.db.playerIdentityClaim.create({data:{suppliedName:input.unlistedPlayerName,normalizedName:normalized,teamId:canonicalTeamId,seasonId:match.seasonId}});return{subjectId:`claim:${claim.id}`,playerId:undefined,identityStatus:'PENDING_RESOLUTION' as const,identityClaim:claim}}throw new BadRequestException('Select a canonical player or provide an unlisted player name and team')}
}
